name: Check Format
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "20"

      - name: Install Prettier
        run: yarn global add prettier

      - name: Check Format
        run: |
          prettier -c "./*/.{js,css,json}"
